---
name: "Close stale issues"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  issues: "write"

jobs:
  stale:
    name: "Close stale issues"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          ascending: false
          any-of-issue-labels: "State: Awaiting Response"
          stale-issue-label: "State: Stale"
          stale-issue-message: "This issue is stale because it has been open 5 days with no activity. Remove stale label or comment or this will be closed in 2 days."
          close-issue-message: "This issue was closed because it has been stale for 2 days with no activity."
          days-before-issue-stale: 5
          days-before-issue-close: 2
          days-before-pr-stale: -1
          days-before-pr-close: -1
          labels-to-remove-when-unstale: "State: Awaiting Response"
