name: Unit

on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - github-actions
      - main
      - 7.16
      - 7.17
      - 6.x
  pull_request:
    branches:
      - main
      - 7.16
      - 7.17
      - 6.x

env:
  GITHUB_ACTIONS: true

jobs:
  test:
    name: "Tests (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go: ['1.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 1 }
      - uses: actions/setup-go@v2.1.3
        with: { go-version: "${{ matrix.go }}" }
      - run: go version
      - run: make test-unit race=true
      - uses: codecov/codecov-action@v1
        with:
          file: tmp/unit.cov
          flags: unit
        if: matrix.os == 'ubuntu-latest'

  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 1 }
      - uses: actions/setup-go@v2.1.3
        with: { go-version: '1.x' }
      - run: go version
      - run: make test-bench
